### ISSUE TITLE
Support for HTTP extensions

### ISSUE THREAD

**Issue by kayex** [adsa95/sirius-api#14]
Add support for submitting and handling [HTTP extensions](https://github.com/kayex/sirius/issues/26).

**Comment by adsa95** [comment]
This was fixed with the following commits, which have currently been merged from feature/http-extensions to develop: 
bb59bff19bfe8944d6eb4b7af0977651c8158287, 9607c485b6e2473fe725275819d2a473079dbe6e, ac7be70955e44981b0921f4b181b9e010c350149, 12181347293a876050a536bef17e0f5340cdfbd6, 3f0d85e90ac6f8d392c5a4cd19b403d0a58739fa, 991973bf56b45b4b8a82deb6c61ee46b8cf64e57

**Comment by adsa95** [comment]
These changes have now been merged into the master branch.
